name: root
publish_to: none

environment:
  sdk: ^3.8.1

workspace:
  - app
  - network
  - shared
  - translate
  - domain
  - tools

dev_dependencies:
  melos:

melos:
  command:
    bootstrap:
      runPubGetInParallel: false

  scripts:
    build_runner_all:
      run: dart pub global run melos exec --concurrency 1 --order-dependents --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner in all packages.

    build_runner_app:
      run: dart pub global run melos exec --fail-fast --scope="*app*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
      description: build_runner build app module.

    build_runner_domain:
      run: dart pub global run melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
      description: build_runner build domain module.

    build_runner_network:
      run: dart pub global run melos exec --fail-fast --scope="*network*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
      description: build_runner build network module.

    build_runner_shared:
      run: dart pub global run melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
      description: build_runner build shared module.

    pub_get_app:
      run: dart pub global run melos exec --fail-fast --scope="*app*" "flutter pub get"
      description: pub get app module.

    pub_get_domain:
      run: dart pub global run melos exec --fail-fast --scope="*domain*" "flutter pub get"
      description: pub get domain module.

    pub_get_network:
      run: dart pub global run melos exec --fail-fast --scope="*network*" "flutter pub get"
      description: pub get network module.

    pub_get_shared:
      run: dart pub global run melos exec --fail-fast --scope="*shared*" "flutter pub get"
      description: pub get shared module.

    l10n:
      run: dart pub global run melos exec --fail-fast --scope="*translate*" --flutter -- dart run intl_utils:generate
      description: Generates l10n for all app packages.