name: domain
description: "A new Flutter project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../shared

  #Model
  freezed_annotation:
  json_annotation:

  auto_route:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:

  #Model
  freezed:
  json_serializable:
