name: app
description: "A new Flutter project."
publish_to: 'none'
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  domain:
    path: ../domain
  shared:
    path: ../shared
  translate:
    path: ../translate
  network:
    path: ../network

  #Flutter Launcher Icons
  flutter_launcher_icons:

  #Flutter Native Splash
  flutter_native_splash:

  flutter_bloc:
  auto_route:
  flutter_screenutil:

  #Dependency Injection
  get_it:
  injectable:

  #Model
  freezed_annotation:
  json_annotation:

  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:
  injectable_generator:
  auto_route_generator:

  #Model
  freezed:
  json_serializable:
  melos:

flutter:

  uses-material-design: true
  assets:
    - env/
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: false
  class_name: S
  main_locale: vi
  arb_dir: lib/translate/l10n
  output_dir: lib/translate/generated