name: translate
description: "A new Flutter project."
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl:

dev_dependencies:
  intl_utils:

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n